export const birthday_data = [
  { img_url: "images/bday_img1.jpeg" },
  { img_url: "images/bday_img2.jpeg" },
  { img_url: "images/bday_img3.jpeg" },
  { img_url: "images/bday_img4.jpeg" },
  { img_url: "images/bday_img5.jpeg" },
  { img_url: "images/bday_img6.jpeg" },
  { img_url: "images/bday_img7.jpeg" },
  { img_url: "images/bday_img8.jpeg" },
  { img_url: "images/bday_img9.jpeg" },
  { img_url: "images/bday_img10.jpeg" },
  { img_url: "images/bday_img11.jpeg" },
  { img_url: "images/bday_img12.jpeg" },
  { img_url: "images/bday_img13.jpeg" },
  { img_url: "images/bday_img14.jpeg" },
  { img_url: "images/bday_img15.jpeg" },
];
export const reception_data = [
  { img_url: "images/rec_img1.jpeg" },
  { img_url: "images/rec_img2.jpeg" },
  { img_url: "images/rec_img3.jpeg" },
  { img_url: "images/rec_img4.jpeg" },
  { img_url: "images/rec_img5.jpeg" },
  { img_url: "images/rec_img6.jpeg" },
  { img_url: "images/rec_img7.jpeg" },
  { img_url: "images/rec_img8.jpeg" },
  { img_url: "images/rec_img9.jpeg" },
  { img_url: "images/rec_img10.jpeg" },
  { img_url: "images/rec_img11.jpeg" },
  { img_url: "images/rec_img12.jpeg" },
  { img_url: "images/rec_img13.jpeg" },
  { img_url: "images/rec_img14.jpeg" },
  { img_url: "images/rec_img15.jpeg" },
  { img_url: "images/rec_img16.jpeg" },
  { img_url: "images/rec_img17.jpeg" },
  { img_url: "images/rec_img18.jpeg" },
  { img_url: "images/rec_img19.jpeg" },
  { img_url: "images/rec_img20.jpeg" },
  { img_url: "images/rec_img21.jpeg" },
  { img_url: "images/rec_img22.jpeg" },
  { img_url: "images/rec_img23.jpeg" },
];
export const wedding_data = [
  { img_url: "images/wed_img1.jpeg" },
  { img_url: "images/wed_img3.jpeg" },
  { img_url: "images/wed_img4.png" },
  { img_url: "images/wed_img5.jpeg" },
  { img_url: "images/wed_img6.jpeg" },
  { img_url: "images/wed_img7.png" },
  { img_url: "images/rec_img20.jpeg" },
  { img_url: "images/wed_img2.jpeg" },
];
export const engagement_data = [
  { img_url: "images/rec_img7.jpeg" },
  { img_url: "images/rec_img11.jpeg" },
  { img_url: "images/rec_img15.jpeg" },
  { img_url: "images/rec_img14.jpeg" },
  { img_url: "images/rec_img16.jpeg" },
  { img_url: "images/rec_img22.jpeg" },
  { img_url: "images/rec_img23.jpeg" },
  { img_url: "images/rec_img2.jpeg" },
  { img_url: "images/rec_img3.jpeg" },
];
